# Optimal hyperparameters for each dataset and method
'00_toy_example',
    'lr':
        'C': 1.0,
        'penalty': 'l2',
        'solver': 'liblinear',
    'rf':
        'n_estimators': 100,
        'max_depth': 3,
        'max_features': 'auto'
    'svm':
        'C': 1.0,
        'kernel': 'rbf',
        'degree': 3,
        'gamma': 'scale',
        'coef0': 0.0,
    'xgb':
        'n_estimators': 100,
        'max_depth': 3,
        'learning_rate': 0.1,
        'subsample': 1.0,

