binary_threshold: 0.5  # Threshold for binary classification
round_digits: 5  # Number of decimal places to round the results to

metrics:
  pd:
    accuracy: True
    brier: True
    f1: True
    precision: True
    recall: True
    aucroc: True
    aucpr: True
    h_measure: True
  lgd:
    mse: True
    mae: True
    r2: True
    rmse: True


