# Description: Dataset selection (only 1 dataset at a time)

dataset_pd:
  00_pd_toydata: false
  #
  01_gmsc: true
  02_taiwan_creditcard: false
  03_vehicle_loan: false
  06_lendingclub: false
  07_case_study: false
  09_myhom: false
  10_hackerearth: false
  11_cobranded: false
  14_german_credit: false
  22_bank_status: false
  28_thomas: false
  29_loan_default: false
  30_home_credit: false
  34_hmeq_data: false

dataset_lgd:
  00_lgd_toydata: false
  #
  01_heloc: false
  03_loss2: false
  05_axa: false
  06_base_model: false
  07_base_modelisation: true



