# Description: Dataset selection (only 1 dataset at a time)

dataset_pd:
  00_pd_toydata: true
  01_gmsc: false
  02_taiwan_creditcard: False
  03_vehicle_loan: False
  29_loan_default: false
  30_home_credit: False
  34_hmeq_data: False

dataset_lgd:
  00_lgd_toydata: True
  01_heloc_lgd: false
  02_heloc_pd: False
  03_loss2: False
  04_extract_bart_baesens_5: False



